# Generated by Django 4.2.3 on 2024-06-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0005_myuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='lastModified_date',
        ),
    ]
